//! Build script.
//!
//! On the `*-windows-gnu` target, rustup's self-contained MinGW is missing some
//! import libraries that eframe/winit need (e.g. `libshlwapi.a`). Ask the system
//! MinGW gcc where one of them lives and add that directory to the link search
//! path, so we don't depend on a machine-specific hardcoded path.

use std::path::Path;
use std::process::Command;

fn main() {
    // Always embed the bundled cleaners so a standalone .exe needs no cleaners/ dir.
    embed_cleaners();

    let is_windows = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");
    if !is_windows {
        return;
    }

    embed_resources();
    add_mingw_lib_path();
}

/// Generate `$OUT_DIR/embedded_cleaners.rs` with `include_str!` for every
/// `cleaners/*.xml`, so the default cleaner set is compiled into the binary and
/// the program runs without a `cleaners/` directory next to it.
fn embed_cleaners() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let cleaners = Path::new(&manifest).join("cleaners");
    println!("cargo:rerun-if-changed={}", cleaners.display());

    let mut files: Vec<_> = std::fs::read_dir(&cleaners)
        .expect("cleaners/ directory must exist")
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .map(|e| e.eq_ignore_ascii_case("xml"))
                .unwrap_or(false)
        })
        .collect();
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs — do not edit.\n\
         pub static EMBEDDED_CLEANERS: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        let name = path.file_name().unwrap().to_string_lossy();
        println!("cargo:rerun-if-changed={}", path.display());
        // Absolute path in a raw string literal; paths never contain a quote.
        out.push_str(&format!(
            "    ({name:?}, include_str!(r\"{}\")),\n",
            path.display()
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("embedded_cleaners.rs");
    std::fs::write(&dest, out).expect("write embedded_cleaners.rs");
}

/// Embed the application icon and manifest (DPI awareness, exec level) into the
/// .exe. Uses `winresource`, which drives `windres` on the GNU toolchain.
fn embed_resources() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    println!("cargo:rerun-if-changed=assets/bbrust.manifest");
    let mut res = winresource::WindowsResource::new();
    res.set_icon("assets/icon.ico");
    res.set_manifest_file("assets/bbrust.manifest");
    if let Err(e) = res.compile() {
        // Don't fail the build on resource-compile issues; just warn.
        println!("cargo:warning=resource embedding failed: {e}");
    }
}

/// rustup's self-contained MinGW lacks some import libraries eframe/winit need
/// (e.g. `libshlwapi.a`). Ask the system MinGW gcc where one lives and add that
/// directory to the link search path.
fn add_mingw_lib_path() {
    if std::env::var("CARGO_CFG_TARGET_ENV").as_deref() != Ok("gnu") {
        return;
    }
    for tool in ["x86_64-w64-mingw32-gcc", "gcc"] {
        if let Ok(out) = Command::new(tool)
            .arg("--print-file-name=libshlwapi.a")
            .output()
        {
            if !out.status.success() {
                continue;
            }
            let printed = String::from_utf8_lossy(&out.stdout);
            let path = Path::new(printed.trim());
            // gcc prints the bare name when it can't find the lib; an absolute
            // path means we found the MinGW lib directory.
            if path.is_absolute() {
                if let Some(dir) = path.parent() {
                    println!("cargo:rustc-link-search=native={}", dir.display());
                }
                return;
            }
        }
    }
}
