//! Build script.
//!
//! On the `*-windows-gnu` target, rustup's self-contained MinGW is missing some
//! import libraries that eframe/winit need (e.g. `libshlwapi.a`). Ask the system
//! MinGW gcc where one of them lives and add that directory to the link search
//! path, so we don't depend on a machine-specific hardcoded path.

use std::path::Path;
use std::process::Command;

fn main() {
    // Always embed the bundled cleaners so a standalone .exe needs no cleaners/ dir.
    embed_cleaners();

    let is_windows = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");
    if !is_windows {
        return;
    }

    embed_resources();
    add_mingw_lib_path();
}

/// Generate `$OUT_DIR/embedded_cleaners.rs` with `include_str!` for every
/// `cleaners/*.xml`, so the default cleaner set is compiled into the binary and
/// the program runs without a `cleaners/` directory next to it.
fn embed_cleaners() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let cleaners = Path::new(&manifest).join("cleaners");
    println!("cargo:rerun-if-changed={}", cleaners.display());

    let mut files: Vec<_> = std::fs::read_dir(&cleaners)
        .expect("cleaners/ directory must exist")
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .map(|e| e.eq_ignore_ascii_case("xml"))
                .unwrap_or(false)
        })
        .collect();
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs — do not edit.\n\
         pub static EMBEDDED_CLEANERS: &[(&str, &str)] = &[\n",
    );
    for path in &files {
        let name = path.file_name().unwrap().to_string_lossy();
        println!("cargo:rerun-if-changed={}", path.display());
        // Absolute path in a raw string literal; paths never contain a quote.
        out.push_str(&format!(
            "    ({name:?}, include_str!(r\"{}\")),\n",
            path.display()
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("embedded_cleaners.rs");
    std::fs::write(&dest, out).expect("write embedded_cleaners.rs");
}

/// Embed the application icon and manifest (DPI awareness, exec level) into the
/// .exe.
///
/// The GNU and MSVC toolchains need different paths:
/// - **GNU** (the local dev machine): drive `windres`/`ar` directly. We can't use
///   the `winresource` crate here because it passes the manifest dir as an
///   unquoted `-I<dir>` to windres' C preprocessor, which splits on the space in
///   this repo's path ("...\GITHUB PROJECTS\...") and aborts with
///   `cc1.exe: fatal error: PROJECTS\bbrust: No such file or directory`, so no
///   resources (icon included) ever get embedded.
/// - **MSVC** (the CI release runner, whose checkout path has no spaces): let
///   `winresource` drive `rc.exe`, since `windres`/`ar` aren't present there.
fn embed_resources() {
    println!("cargo:rerun-if-changed=assets/icon.ico");
    println!("cargo:rerun-if-changed=assets/bbrust.manifest");

    if std::env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("gnu") {
        embed_resources_gnu();
    } else {
        embed_resources_winresource();
    }
}

/// MSVC path: `winresource` → `rc.exe`. Used on CI; relies on a space-free path.
fn embed_resources_winresource() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let icon = Path::new(&manifest_dir).join("assets/icon.ico");
    let app_manifest = Path::new(&manifest_dir).join("assets/bbrust.manifest");
    let mut res = winresource::WindowsResource::new();
    res.set_icon(&icon.to_string_lossy());
    res.set_manifest_file(&app_manifest.to_string_lossy());
    if let Err(e) = res.compile() {
        // Don't fail the build on resource-compile issues; just warn.
        println!("cargo:warning=resource embedding failed: {e}");
    }
}

/// GNU path: generate a `.rc` with quoted, forward-slash absolute paths and drive
/// `windres`/`ar` ourselves, sidestepping winresource's broken `-I` quoting.
fn embed_resources_gnu() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = std::env::var("OUT_DIR").unwrap();
    // Forward slashes work for both windres' file resolution and `.rc` quoting,
    // and a space inside a quoted resource path is handled fine by windres.
    let to_rc = |p: &Path| p.to_string_lossy().replace('\\', "/");
    let icon = to_rc(&Path::new(&manifest_dir).join("assets/icon.ico"));
    let app_manifest = to_rc(&Path::new(&manifest_dir).join("assets/bbrust.manifest"));

    let rc_path = Path::new(&out_dir).join("resource.rc");
    let rc = format!("1 ICON \"{icon}\"\n1 24 \"{app_manifest}\"\n");
    if let Err(e) = std::fs::write(&rc_path, rc) {
        println!("cargo:warning=could not write resource.rc: {e}");
        return;
    }

    // windres -> resource.o, then ar -> libresource.a, linked whole-archive so
    // the linker keeps the resource section even though nothing references it.
    let obj = Path::new(&out_dir).join("resource.o");
    if !run_tool(
        &["x86_64-w64-mingw32-windres", "windres"],
        &out_dir,
        &[
            "--target",
            "pe-x86-64",
            "-i",
            &rc_path.to_string_lossy(),
            "-o",
            &obj.to_string_lossy(),
        ],
        "windres",
    ) {
        return;
    }

    let lib = Path::new(&out_dir).join("libresource.a");
    if !run_tool(
        &["x86_64-w64-mingw32-ar", "ar"],
        &out_dir,
        &["rcs", &lib.to_string_lossy(), &obj.to_string_lossy()],
        "ar",
    ) {
        return;
    }

    println!("cargo:rustc-link-search=native={out_dir}");
    println!("cargo:rustc-link-lib=static:+whole-archive=resource");
}

/// Run the first of `candidates` that exists, with the given args and cwd.
/// Returns true on success; warns (but doesn't fail the build) otherwise.
fn run_tool(candidates: &[&str], cwd: &str, args: &[&str], label: &str) -> bool {
    for tool in candidates {
        match Command::new(tool).current_dir(cwd).args(args).status() {
            Ok(status) if status.success() => return true,
            Ok(status) => {
                println!("cargo:warning={label} ({tool}) failed with {status}");
                return false;
            }
            Err(_) => continue, // tool not found under this name; try the next
        }
    }
    println!("cargo:warning={label} not found (tried {candidates:?}); icon not embedded");
    false
}

/// rustup's self-contained MinGW lacks some import libraries eframe/winit need
/// (e.g. `libshlwapi.a`). Ask the system MinGW gcc where one lives and add that
/// directory to the link search path.
fn add_mingw_lib_path() {
    if std::env::var("CARGO_CFG_TARGET_ENV").as_deref() != Ok("gnu") {
        return;
    }
    for tool in ["x86_64-w64-mingw32-gcc", "gcc"] {
        if let Ok(out) = Command::new(tool)
            .arg("--print-file-name=libshlwapi.a")
            .output()
        {
            if !out.status.success() {
                continue;
            }
            let printed = String::from_utf8_lossy(&out.stdout);
            let path = Path::new(printed.trim());
            // gcc prints the bare name when it can't find the lib; an absolute
            // path means we found the MinGW lib directory.
            if path.is_absolute() {
                if let Some(dir) = path.parent() {
                    println!("cargo:rustc-link-search=native={}", dir.display());
                }
                return;
            }
        }
    }
}
